language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8
install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install -e .[test]
- pip install -e .[setup]
script:
- python setup.py test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: adobeDan
  password:
    secure: nqS9f74jOJZnZ7FqhwpChvP4MlslIF14StxxdYrMuKs0fh6Bcz8O5DROBiEEs9OvM3+cbPkmfkg7PKkZQx4UQTQzYCPKV85YegrQW2WRcwwW3ik6NB5AELphjx3RBMA61p827m7V4vHW67j70+ITDG1joKBNzj7XfQPNma4LtBAxNPsNP9sHaZsWAUAnBvDZ9m7s3mPp2x3t+f9klxaurW7V6NvrjB47r9ln5Ry2JWxHBPKBjJ4XgVVYVQF4HmyrOzszH6xYUVS1KY6S6RUeOl8u/PwSWh3/QH0TvNmVzuZgU/dZxF0JEJbFZvh6+tVNaCcCGYlF+bXkPKbeMEnnPPvaI1RHuUbplPhNWRjVSksAJsznbvYseSg/e7yGJ6ghpsVAySqamMzrpH+U2OJ09czxv3boo9zJm/WWwg069OYkKWyUpNdjgiz0mgYb4KfVak0qhVy3qtbxju4RdCRnxIM2TXF+G/nkUpgtoSFgydgVpMbU2hjj8nonPgesWthFs9KlZocW1epyGySUVvcOcp4KuSvxS3njmA0+knWkAnCvFv7ynCkx7V7CNZvMo49HSMxNGfEs+d12MGIbfqYpIa1van8m4ApOuZ8RhVQq0ZLxVyuORqIDrG1PO7Gg/FFn4objp7e850lBML5ruoMqTmr5FFNSSBXfO/3NQa7l9RM=
  on:
    tags: true
    python: "3.6"
    repo: adobe-apiplatform/umapi-client.py
    all_branches: true
